version: "3"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - ml-service
      - mongo

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
